apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list: 
        elements:
          - env: beta
          - env: rc
          - env: prod
  template:
    metadata:
      name: app-{{ .env }}
    spec:
      project: default
      source:
        repoURL: https://github.com/wingyplus/argolabs-devops.git
        targetRevision: HEAD
        path: environments/{{ .env }}
      destination:
        server: https://kubernetes.default.svc
        namespace: argolabs-{{ .env }}
      syncPolicy:
        automated: 
          selfHeal: true
