apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app
  labels:
    app: app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/wingyplus/argolabs/app:latest
          ports:
            - containerPort: 4000
          env:
            - name: SECRET_KEY_BASE
              # TODO: don't do this in real production workloads!
              value: FAeQc29JiqbXZKbSPGLaAg3E10eT7iynSupeOQQeUlswNSZ+4I9BwuLCaTHMMxmC
