apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argolabs-test
resources:
- deployment.yaml
images:
- digest: sha256:cfe575d352307de0957cc3da35dc898faa7fc7cd2fc28d1dac89d107a3d9d863
  name: ghcr.io/wingyplus/argolabs/app
  newTag: 0.1.0-2
